# Generated by Django 4.1.5 on 2023-01-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yahrzeit_app", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
