# Generated by Django 4.1.5 on 2023-01-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahrzeit_app', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='decedent',
            name='next_date_hebrew',
            field=models.CharField(default='2020-12-12', max_length=10),
            preserve_default=False,
        ),
    ]
