# Generated by Django 4.1.5 on 2023-01-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yahrzeit_app", "0004_decedent_next_date_hebrew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decedent",
            name="next_date_gregorian",
            field=models.CharField(max_length=10),
        ),
    ]
