# Generated by Django 4.1.7 on 2023-03-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yahrzeit_app", "0005_alter_decedent_next_date_gregorian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
