# Generated by Django 4.1.7 on 2023-03-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yahrzeit_app", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
